# Generated by Django 6.0 on 2025-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('diesel', 'Diesel'), ('electricity', 'Electricity'), ('explosives', 'Explosives'), ('transport', 'Transport')], max_length=20)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('co2_per_unit', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
